### ISSUE TITLE
Design key bindings for spell crafting and usage

### ISSUE THREAD

**Issue by VinayGupta23** [powenyao/SpellCrafter#12]
The new input system is being used. Need to define new bindings and add input manager to switch between crafting and casting mode.

**Comment by powenyao** [comment]
![image](https://user-images.githubusercontent.com/15680545/216707974-28399cb9-3a09-45a9-adc8-92a3cad00d9b.png)

We can do hybrid to make things easier

**Comment by VinayGupta23** [comment]
If it helps with debugging then sure!
But for the released game itself let's ensure to use "New" so we can setup input manager easily.
