### ISSUE TITLE
Spell tracking component for "homing" to nearest enemy

### ISSUE THREAD

**Issue by VinayGupta23** [powenyao/SpellCrafter#8]
Decide the quality level for tracking, i.e. how effective will it be?

**Comment by powenyao** [comment]
@tyang863 if you are joining us
Missile.cs
MissileLauncher.cs
spell_shootable_projectile.cs/SpellBase.cs has TrackingTarget()

We want it to work in 3 versions.
None, partial, and full.
Partial will make adjustment to hit the target, but if it misses, oh well. 
Full will keep flying until it hits. 

Aside from needing it to fly for longer (which we might not actually want), it's mostly about its rotation speed compared to movement speed. Full would likely be able to make really sharp turns.
