### ISSUE TITLE
Basic enemy to test spells

### ISSUE THREAD

**Issue by VinayGupta23** [powenyao/SpellCrafter#9]
Enemy should support: HP, element created from, handle spawn/death

**Comment by powenyao** [comment]
A basic version is now pushed as "PF_Target_Base" and its variant "PF_Target_Cube"
The work is done in the script ShootingTarget.cs which implements the interface IDamageReceiver.
In the inspector, you can select its starting element.
After being hit by something that implements the interface IDamageDealer, it will take damage and destroy itself if too much damage.
